[[edge_functions]]
function = "share-og"
path = "/share/*"

[[redirects]]
  from = "/share/*"
  to = "/share/:splat"
  status = 200
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200